<div class="jumbotron">
    <h1 class="display-4">Bem Vindo ao Projeto 2!</h1>
    <p class="lead">
        Projeto criado no curso PHP Orientado a Objetos da Code Experts Learning
    </p>
    <hr class="my-4">
    <a class="btn btn-primary btn-lg" href="/" role="button">Saiba Mais</a>
</div>
<div class="row">
    <?php foreach ($this->products as $product) : ?>
        <div class="col-4">
            <img src="http://via.placeholder.com/350x150?text=<?= $product['name'];?>" alt="" class="img-fluid">
            <h2><a href="<?= HOME;?>/product/<?= $product['id'];?>"><?= $product['name'];?></a></h2>
            <p><?= $product['description'];?></p>
            <p><?= number_format($product['price'], 2, ',', '.');?></p>
        </div>
    <?php endforeach; ?>
</div>
