<div class="row">
    <div class="col-6">
        <img src="http://via.placeholder.com/600x350?text=<?= $this->product['name'];?>" alt="" class="img-fluid">
    </div>
    <div class="col-6">
        <h2><a href="<?= HOME;?>/product/<?= $this->product['id'];?>"><?= $this->product['name'];?></a></h2>
        <p><?= $this->product['description'];?></p>
        <p>R$ <?=number_format($this->product['price'], 2, ',', '.');?></p>
    </div>
</div>
