<div class="row justify-content-center">
    <div class="col-6">
        <h2>USUÁRIOS - <small>Cadastrar novo usuário</small></h2>
        <hr>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-8">
        <?php require VIEWS_PATH . 'includes' . DIRECTORY_SEPARATOR . 'messages.phtml'; ?>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-6">
        <form method="POST" action="<?= HOME;?>/users/new">
            <div class="form-group">
                <label for="exampleInputEmail1">Nome</label>
                <input name="first_name" type="text" class="form-control form-control-sm">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Sobrenome</label>
                <input name="last_name" type="text" class="form-control form-control-sm">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Username</label>
                <input name="username" type="text" class="form-control form-control-sm">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Senha</label>
                <input name="password" type="password" class="form-control form-control-sm">
            </div>
             <div class="form-group">
                <label for="exampleInputEmail1">Cofirmar Senha</label>
                <input name="password_confirm" type="password" class="form-control form-control-sm">
            </div>
            <button type="submit" class="btn btn-success btn-sm float-right">Salvar Usuário</button>
        </form>
    </div>
</div>