<?php require VIEWS_PATH . DS . 'admin' . DS . 'includes' . DS . 'header.phtml'; ?>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>Criar Produto</h2>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <?php require VIEWS_PATH . 'includes/messages.phtml';?>
            </div>
        </div>

        <div class="row">
            <form action="<?= HOME;?>/admin/products/new" method="POST" enctype="multipart/form-data">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Nome do produto</label>
                        <input name="name" class="form-control" type="text">
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="form-group">
                        <label>Descrição</label>
                        <input name="description" class="form-control" type="text">
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="form-group">
                        <label>Conteúdo</label>
                        <textarea name="content" class="form-control" rows="5"></textarea>
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Preço</label>
                                <input name="price" class="form-control" type="text">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Status produto</label>
                                <select name="is_active" class="form-control">
                                    <option value="A">Ativo</option>
                                    <option value="I">Inativo</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="form-group">
                        <label>Selecione as imagens do produto</label>
                        <input name="images[]" class="form-control" type="file" multiple>
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="form-group">
                        <label>Selecione as categorias para este produto</label>
                        <select class="form-control" name="categories[]" multiple>
                            <?php foreach ($this->categories as $category) : ?>
                                <option value="<?=$category['id'];?>"><?=$category['name'];?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <div class="col-md-12">
                    <button type="submit" class="btn btn-lg btn-success pull-right">Criar Produto</button>
                </div>
            </form>


        </div>

    </div>
<?php require VIEWS_PATH . 'admin/includes/footer.phtml';?>
