<div class="row justify-content-center">
    <div class="col-6">
        <h2>EDITAR DESPESA</h2>
        <hr>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-6">
        <form method="POST" action="<?= HOME;?>/myexpenses/edit/<?= $this->expense['id'];?>">
            <div class="form-group">
                <label for="exampleInputEmail1">Valor Gasto</label>
                <input name="value" type="text" class="form-control form-control-sm" id="exampleInputEmail1" placeholder="Valor gasto" value="<?= $this->expense['value'];?>">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Categoria</label>
                <select class="form-control form-control-sm" name="categories_id">
                    <?php foreach($this->categories as $category) :?>
                        <option value="<?= $category['id'];?>"
                            <?php if ($category['id'] == $this->expense['categories_id']) : ?>
                                selected
                            <?php endif; ?>
                        ><?= $category['name'];?></option>
                    <?php endforeach;?>
                </select>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Usuários</label>
                <select class="form-control form-control-sm" name="users_id">
                    <?php foreach($this->users as $user) :?>
                        <option value="<?= $user['id'];?>"
                            <?php if ($user['id'] == $this->expense['users_id']) : ?>
                                selected
                            <?php endif; ?>
                        ><?= $user['first_name'];?></option>
                    <?php endforeach;?>
                </select>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Descrição</label>
                <textarea name="description" class="form-control" rows="3" value="<?= $this->expense['description'];?>"><?= $this->expense['description'];?></textarea>
            </div>
            <button type="submit" class="btn btn-success btn-sm float-right">Atualizar Despesa</button>
        </form>
    </div>
</div>