<div class="row justify-content-center mt-4">
    <div class="col">
        <h2>SUAS DESPESAS</h2>
        <hr>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Descrição</th>
                    <th>Valor</th>
                    <th>Criado em</th>
                    <th>Criado em</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->expenses as $expense) :?>
                <tr>
                    <td><?= $expense['id'];?></td>
                    <td><?= $expense['description'];?></td>
                    <td>R$ <?= number_format($expense['value'], 2, ',', '.');?></td>
                    <td><?= (new \DateTime($expense['created_at'], new \DateTimeZone('America/Sao_Paulo')))->format("d/m/Y H:i:s");?></td>
                    <td>
                        <a href="<?= HOME;?>/myexpenses/edit/<?= $expense['id'];?>" class="btn btn-light">Editar</a>
                        <a href="<?= HOME;?>/myexpenses/remove/<?= $expense['id'];?>" class="btn btn-danger">Excluir</a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>