<div class="row justify-content-center mt-4">
    <div class="col">
        <h2>CATEGORIAS <small>Gerencie suas categorias</small></h2>
        <hr>
    </div>
</div>
<div class="row">
    <div class="col-8">
        <?php require VIEWS_PATH . 'includes' . DIRECTORY_SEPARATOR . 'messages.phtml'; ?>
    </div>
    <div class="col-4">
        <a href="<?= HOME;?>/categories/new" class="btn btn-sm float-right btn-primary py-1">Nova Categoria</a>
    </div>
</div>
<div class="row justify-content-center mt-4">
    <div class="col">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Criado em</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->categories as $category) :?>
                <tr>
                    <td><?= $category['id'];?></td>
                    <td><?= $category['name'];?></td>
                    <td><?= (new \DateTime($category['created_at'], new \DateTimeZone('America/Sao_Paulo')))->format("d/m/Y H:i:s");?></td>
                    <td>
                        <a href="<?= HOME;?>/categories/edit/<?= $category['id'];?>" class="btn btn-light">Editar</a>
                        <a href="<?= HOME;?>/categories/remove/<?= $category['id'];?>" class="btn btn-danger">Excluir</a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>