<div class="row justify-content-center">
    <div class="col-6">
        <h2>CATEGORIAS - <small>Cadastrar nova categoria</small></h2>
        <hr>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-8">
        <?php require VIEWS_PATH . 'includes' . DIRECTORY_SEPARATOR . 'messages.phtml'; ?>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-6">
        <form method="POST" action="<?= HOME;?>/categories/new">
            <div class="form-group">
                <label for="exampleInputEmail1">Nome</label>
                <input name="name" type="text" class="form-control form-control-sm">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Descrição</label>
                <textarea name="description" class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-success btn-sm float-right">Salvar Categoria</button>
        </form>
    </div>
</div>