<div class="row justify-content-center">
    <div class="col-6">
        <h2>POSTS - <small>Cadastrar nova postagem</small></h2>
        <hr>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-8">
        <?php require VIEWS_PATH . 'includes' . DIRECTORY_SEPARATOR . 'messages.phtml'; ?>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-6">
        <form method="POST" action="<?= HOME;?>/posts/new">
            <div class="form-group">
                <label for="exampleInputEmail1">Título</label>
                <input name="title" type="text" class="form-control form-control-sm">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Descrição</label>
                <input name="description" type="text" class="form-control form-control-sm">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Conteúdo</label>
                <textarea name="content" class="form-control" rows="3"></textarea>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Slug</label>
                <input name="slug" type="text" class="form-control form-control-sm">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Tipo</label>
                <select name="type" class="form-control form-control-sm">
                    <option value="">Selecione o tipo do conteúdo</option>
                    <option value="post">Post</option>
                    <option value="page">Página</option>
                </select>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Tipo</label>
                <select name="user_id" class="form-control form-control-sm">
                    <option value="">Selecione o autor</option>
                    <?php foreach($this->users as $user) : ?>
                        <option value="<?=$user['id']?>"> <?=$user['first_name'] . ' ' . $user['last_name'];?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <button type="submit" class="btn btn-success btn-sm float-right">Salvar Post</button>
        </form>
    </div>
</div>