<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Projeto 3 - Controle de Gastos</title>
        <link type="text/css" rel="stylesheet" href="<?= CSS_PATH;?>bootstrap.min.css">
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light mb-2">
                <a class="navbar-brand" href="<?= HOME;?>/">Code Experts Learning - Catálogo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= HOME;?>/">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= HOME;?>/posts">Blog</a>
                        </li>
                        <?php if (\Code\Session\Session::has('user')) : ?>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= HOME;?>/auth/logout">Sair</a>
                            </li>
                        <?php else: ?>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= HOME;?>/auth/login">Login</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </nav>