<div class="row">
    <div class="col-2">
        <a href="<?= HOME;?>" class="btn btn-sm btn-block btn-warning">Voltar</a>
    </div>
</div>
<div class="row mt-4">
    <div class="col-8">
        <h1><?= $this->category;?></h1>
        <hr>
        <?php foreach($this->posts as $post) : ?>
            <div class="row">
                <div class="col">
                    <h2>
                        <a href="<?= HOME . DIRECTORY_SEPARATOR . 'post' . DIRECTORY_SEPARATOR . $post['slug'];?>" title="">
                            <?= $post['title'];?>
                        </a>
                    </h2>
                    <small>Criado em <?= (new \DateTime($post['created_at'], new \DateTimeZone('America/Sao_Paulo')))->format("d/m/Y H:i:s");?></small>
                    <p><?= $post['description'];?></p>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="col-4 px-5">
        <h3>Sidebar</h3>
        <hr>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
    </div>
</div>
