<div class="row">
    <div class="col">
        <div class="jumbotron">
            <h1 class="display-4">Contato</h1>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <h2>Fale Conosco por meio dos contatos abaixo!</h2>
        <p>
            Telefone: <a href="tel:44999999999"><strong>44 9 9999 9999</strong></a> <br>
            Email: <a href="mailto:email@email.con"><strong>email@email.com</strong></a> <br>
        </p>
        <p>
            Ou através do form abaixo:
            <form>
              <div class="form-group">
                <label for="exampleInputEmail1">Nome</label>
                <input type="text" class="form-control form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Digite o nome aqui">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Email</label>
                <input type="email" class="form-control" id="exampleInputPassword1" placeholder="email@exemplo.com">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Mensagem</label>
                <textarea class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
        </p>
    </div>
</div>
