        </div> <!-- container -->
        <footer>
            <div class="container text-center">
            <hr>
                Projeto Code Experts Learning &copy; Todos os Direitos Reservados - <?= date('Y');?>
            </div>
        </footer>
        <script type="text/javascript" src="<?= JS_PATH;?>jquery-3.4.1.min.js"></script>
        <script type="text/javascript" src="<?= JS_PATH;?>bootstrap.min.js"></script>
    </body>
</html>